name: درخواست عضویت درکتابخانه آزاد
description: با پر کردن این فرم درخواست عضویت خود را مبنی بر نویسنده بودن در این کتابخانه اعلام می‌کنید.
title: "درخواست عضویت: "
labels: ["عضویت"]
assignees:  # assign to core
  - metantesan
  - behdanisohrab
body:
  - type: markdown
    attributes:
      value: |
        از اینکه مایل به نوشتن کتاب در این کتابخانه هستید سپاس‌گذاریم.
  - type: textarea
    id: name
    attributes:
      label: نام و نام خانوادگی و راه های ارتباطی
      description: می‌خواهیم شمارا بیشتر بشناسیم
      placeholder: برای مثال: سعید سعیدی
      value: "name-and-surname"
    validations:
      required: true
  - type: textarea
    id: book
    attributes:
      label: مایل به نوشتن چه کتابی هستید؟
      description: توضیحاتی از کتابی که می‌خواهید بنویسید به ما بدهید.
    validations:
      required: true
  - type: dropdown
    id: service
    attributes:
      label: کتابتان را تحت چه اجازه‌نامه‌ای عرضه می‌کنید؟
      multiple: false
      options:
        - CC-BY-SA (Creative Commons Attribution-ShareAlike)
        - Creative Commons NonCommercial license (CC NC, CC BY-NC or NC license)
  - type: checkboxes
    id: terms
    attributes:
      label: پذیرفتن قوانین
      description: با ثبت این درخواست شما با  [قوانین](https://github.com/persianccbook/.github/blob/main/agreement.md) ما موافقت می‌کنید.
      options:
        - label: من قوانین را خواندم و با آن موافقم.
          required: true
